package p2p

import (
	"bufio"
	"bytes"
	"encoding/hex"
	"encoding/json"
	"net"
	"os"
	"testing"
	"time"

	"github.com/craig/constella/explorer/internal/proto"
)

// Generated by the C protocol probe; the Python lab independently checks
// genesis, transaction domains, transcript layout and keyed BLAKE2b inputs.
func networkVector(t *testing.T) map[string]string {
	t.Helper()
	raw, err := os.ReadFile("../../../tests/fixtures/network-profiles.json")
	if err != nil {
		t.Fatal(err)
	}
	var all map[string]map[string]json.RawMessage
	if err := json.Unmarshal(raw, &all); err != nil {
		t.Fatal(err)
	}
	v, ok := all[proto.NetworkHeader]
	if !ok {
		t.Fatal("missing active network vector")
	}
	out := make(map[string]string)
	for k, raw := range v {
		var value string
		if json.Unmarshal(raw, &value) == nil {
			out[k] = value
		}
	}
	return out
}

func TestNetworkBoundTranscript(t *testing.T) {
	v := networkVector(t)
	a, b := unhex(t, vecEphAPub), unhex(t, vecEphBPub)
	ia, ib := bytes.Repeat([]byte{0xaa}, 32), bytes.Repeat([]byte{0x55}, 32)
	tr := boundTranscript(a, b, ia, ib)
	if hex.EncodeToString(tr) != v["transcript"] {
		t.Fatal("C/Go transcript mismatch")
	}
	if !eddsaVerify(unhex(t, v["pub"]), unhex(t, v["signature"]), tr) {
		t.Fatal("C signature rejected")
	}
	if proto.ShareVersion >= 4 {
		if len(tr) != 148 {
			t.Fatal("wrong candidate transcript size")
		}
		// Every byte of the label, network, ephemerals and identities is signed.
		for i := range len(tr) {
			changed := bytes.Clone(tr)
			changed[i] ^= 1
			if eddsaVerify(unhex(t, v["pub"]), unhex(t, v["signature"]), changed) {
				t.Fatalf("unsigned transcript byte %d", i)
			}
		}
	}
}

func TestNetworkCInterop(t *testing.T) {
	addr := os.Getenv("CONSTELLA_TEST_PEER")
	if addr == "" {
		t.Skip("isolated C node supplied by make protocol-test")
	}
	conn, err := net.DialTimeout("tcp", addr, 3*time.Second)
	if err != nil {
		t.Fatal(err)
	}
	defer conn.Close()
	id, err := newIdentity(bytes.Repeat([]byte{0x91}, 32))
	if err != nil {
		t.Fatal(err)
	}
	r := bufio.NewReader(conn)
	s, err := staticHandshake(conn, r, id)
	if err != nil {
		t.Fatal(err)
	}
	if err := conn.SetDeadline(time.Now().Add(3 * time.Second)); err != nil {
		t.Fatal(err)
	}
	for _, typ := range []byte{proto.MsgHello, proto.MsgGetAcct} {
		if err := writeAll(conn, sealFrame(s, typ, make([]byte, 32))); err != nil {
			t.Fatal(err)
		}
	}
	for range 3 {
		typ, payload, err := readSecure(r, s)
		if err != nil {
			t.Fatal(err)
		}
		if typ == proto.MsgAcct {
			if len(payload) != 28 {
				t.Fatal("wrong account response")
			}
			return
		}
	}
	t.Fatal("no encrypted account response")
}
