#!/usr/bin/env python3
"""Destructive persistence probes, confined to a new disposable Compose lab.

Inputs are a public shares.v3 and its successful gate_snapshot JSON. Never
copy live wallet/node keys. All lab keys are generated by the shipped node.
The caller retains evidence and stopped containers; no live stack is touched.
"""
import argparse
import hashlib
import json
import os
from pathlib import Path
import subprocess
import time


def run(args, **kwargs):
    return subprocess.run(args, check=True, capture_output=True, text=True, **kwargs)


def digest(data):
    return hashlib.sha256(data).hexdigest()


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument('shares', type=Path)
    ap.add_argument('snapshot', type=Path)
    ap.add_argument('directory', type=Path)
    ap.add_argument('--image', default='constella:gate2-sync-fix-20260928')
    ap.add_argument('--reader', type=Path, default=Path('./gate_snapshot'))
    args = ap.parse_args()
    root = args.directory.resolve()
    root.mkdir(mode=0o700)  # Refuse to overwrite or reuse an existing lab.
    project = 'constella-gate3-' + root.name.lower().replace('_', '-')
    compose = root / 'compose.json'
    dc = ['docker', 'compose', '-p', project, '-f', str(compose)]
    source = args.shares.read_bytes()
    snap = json.loads(args.snapshot.read_text())
    canonical = {x['id']: x['height'] for x in snap['entries'] if x['canonical']}
    records = {}
    offset = 0
    while offset < len(source):
        length = int.from_bytes(source[offset:offset+2], 'little')
        record = source[offset:offset+2+length]
        assert length >= 128 and len(record) == length + 2
        sid = hashlib.blake2b(record[2:126], digest_size=32).hexdigest()
        if sid in canonical and canonical[sid] <= 1024:
            records[canonical[sid]] = record
        offset += length + 2
    assert sorted(records) == list(range(1, 1025))
    reference = b''.join(records[h] for h in range(1, 1025))
    prefix = b''.join(records[h] for h in range(1, 750))
    middle = bytearray(reference)
    middle[len(prefix)+2] ^= 1  # Share version: valid framing, invalid consensus.
    cases = {
        'short-length': (reference + b'\x80', reference),
        'short-body': (reference + records[1024][:30], reference),
        'bad-length': (reference + b'\xff\xff', reference),
        'bad-middle': (bytes(middle), prefix),
        'duplicate': (prefix + records[749] + reference[len(prefix):], prefix),
        'peer-cache': (reference, reference),
        'crash': (b'', b''),
        'wallet-bad': (b'', b''),
        'identity-bad': (b'', b''),
        'readonly': (reference + b'\x80', None),
    }
    services = {}
    for name, (payload, _) in {'seed': (reference, reference), **cases}.items():
        data = root / name
        data.mkdir(mode=0o700)
        (data / 'shares.v3').write_bytes(payload)
        volumes = [f'{data}:/data']
        if name == 'readonly':
            volumes.append(f'{data}/shares.v3:/data/shares.v3:ro')
        services[name] = {
            'image': args.image, 'restart': 'no', 'cpus': 1.0,
            'user': f'{os.getuid()}:{os.getgid()}',
            'environment': {
                'CONSTELLA_THREADS': '1', 'CONSTELLA_DUTY': '0',
                'CONSTELLA_PRIVATE_NET': '1', 'CONSTELLA_PEERS': '',
                'CONSTELLA_BATTERY_PAUSE': '1',
            },
            'volumes': volumes, 'networks': ['lab'],
        }
    (root / 'wallet-bad/wallet.key').write_bytes(b'invalid-key\n')
    (root / 'identity-bad/node.key').write_bytes(b'invalid-key\n')
    # Structurally invalid cache; no live peer-table secret enters the lab.
    (root / 'peer-cache/peers.dat').write_bytes(b'ADR1\x01broken-checksum')
    compose.write_text(json.dumps({'services': services,
                                 'networks': {'lab': {'internal': True}}}, indent=2))
    result = {'image': args.image, 'source_sha256': digest(source),
              'image_id': run(['docker', 'image', 'inspect', '--format', '{{.Id}}', args.image]).stdout.strip(),
              'reference_height': 1024, 'cases': {}, 'crash_cycles': []}

    def save():
        (root / 'result.json').write_text(json.dumps(result, indent=2) + '\n')

    def logs(name):
        p = run(dc + ['logs', '--no-color', name])
        return p.stdout + p.stderr

    def wait_for(predicate, label, timeout=180):
        deadline = time.monotonic() + timeout
        while time.monotonic() < deadline:
            if predicate():
                return
            time.sleep(0.25)
        raise RuntimeError('timeout: ' + label)

    def ready(name):
        return 'constella: payout=' in logs(name)

    def inspect(name):
        cid = run(dc + ['ps', '-aq', name]).stdout.strip()
        return json.loads(run(['docker', 'inspect', cid]).stdout)[0]

    def snapshot(name, source=None):
        p = run([str(args.reader.resolve()), str(source or root / name / 'shares.v3')])
        (root / (name + '-snapshot.json')).write_text(p.stdout)
        return json.loads(p.stdout)

    try:
        # No peers configured yet: inspect exact on-disk repair before sync.
        for name in cases:
            run(dc + ['up', '-d', '--no-deps', name])
            if name in ('wallet-bad', 'identity-bad', 'readonly'):
                wait_for(lambda: not inspect(name)['State']['Running'], name)
                state = inspect(name)['State']
                assert state['ExitCode'] != 0 and 'fatal:' in logs(name)
                assert (root / name / 'shares.v3').read_bytes() == cases[name][0]
                if name != 'readonly':
                    key = 'wallet.key' if name == 'wallet-bad' else 'node.key'
                    assert (root / name / key).read_bytes() == b'invalid-key\n'
                result['cases'][name] = {'fail_closed': True, 'exit_code': state['ExitCode']}
            else:
                wait_for(lambda: ready(name), name)
                run(dc + ['stop', '-t', '10', name])
                assert (root / name / 'shares.v3').read_bytes() == cases[name][1], name
                result['cases'][name] = {'validated_prefix_exact': True,
                                        'prefix_bytes': len(cases[name][1])}
                if name == 'peer-cache':
                    peer = (root / name / 'peers.dat').read_bytes()
                    assert peer[:5] == b'ADR1\x01'
                    assert hashlib.blake2b(peer[:-32], digest_size=32).digest() == peer[-32:]
                    result['cases'][name]['cache_checksum_repaired'] = True
            (root / (name + '-initial.log')).write_text(logs(name))
            save()
            print('initial PASS', name, flush=True)

        run(dc + ['up', '-d', '--no-deps', 'seed'])
        wait_for(lambda: ready('seed'), 'seed')
        healthy = [n for n in cases if n not in ('wallet-bad', 'identity-bad', 'readonly')]
        identities = {n: {k: digest((root/n/k).read_bytes())
                          for k in ('wallet.key', 'node.key')} for n in healthy}
        for n in healthy:
            services[n]['environment']['CONSTELLA_PEERS'] = 'seed:7043'
        compose.write_text(json.dumps({'services': services,
                                     'networks': {'lab': {'internal': True}}}, indent=2))
        # Kill during incoming append, during startup, then after full sync.
        run(dc + ['up', '-d', '--no-deps', 'crash'])
        wait_for(lambda: (root/'crash/shares.v3').stat().st_size > 10000, 'incoming records')
        for phase in ('incoming-sync', 'startup-replay', 'caught-up-1', 'caught-up-2'):
            if phase.startswith('caught-up'):
                wait_for(lambda: (root/'crash/shares.v3').stat().st_size >= len(reference), phase)
            before = (root/'crash/shares.v3').stat().st_size
            run(dc + ['kill', '-s', 'SIGKILL', 'crash'])
            state = inspect('crash')['State']
            assert state['ExitCode'] == 137, state
            result['crash_cycles'].append({'phase': phase, 'bytes_before_kill': before,
                                           'exit_code': state['ExitCode']})
            save()
            run(dc + ['start', 'crash'])
            if phase == 'incoming-sync':
                time.sleep(0.05)
        run(dc + ['up', '-d', '--no-deps'] + [n for n in healthy if n != 'crash'])
        for name in healthy:
            wait_for(lambda: (root/name/'shares.v3').stat().st_size >= len(reference), name+' sync')
            run(dc + ['stop', '-t', '10', name])
            recovered = (root/name/'shares.v3').read_bytes()
            assert recovered.startswith(reference), name+' recovered history differs'
            assert all(digest((root/name/k).read_bytes()) == v for k,v in identities[name].items())
            result['cases'][name].update(recovered_exact_chain=True, identities_preserved=True)
            # A subsequent clean restart must retain the fully repaired chain.
            starts = logs(name).count('constella: payout=')
            run(dc + ['start', name])
            wait_for(lambda: logs(name).count('constella: payout=') > starts,
                     name+' second restart')
            run(dc + ['stop', '-t', '10', name])
            assert (root/name/'shares.v3').read_bytes().startswith(recovered)
            result['cases'][name]['second_restart_durable'] = True
            (root/(name+'-final.log')).write_text(logs(name))
            save()
            print('recovery PASS', name, flush=True)
        run(dc + ['stop', '-t', '10', 'seed'])
        # A running seed can append new valid shares. Validate each entire
        # file, then compare the exact recovered prefix at a common height;
        # an extension is not corruption or a recovery failure.
        baseline = root / 'reference.v3'
        baseline.write_bytes(reference)
        ref = snapshot('reference', baseline)
        assert ref['height'] == 1024
        for name in healthy:
            got = snapshot(name)
            assert got['height'] >= ref['height']
            canonical = [x for x in got['entries'] if x['canonical']
                         and x['height'] <= ref['height']]
            expected = [x for x in ref['entries'] if x['canonical']]
            assert [(x['height'], x['id']) for x in canonical] == [
                (x['height'], x['id']) for x in expected]
            common = root / (name+'-common.v3')
            common.write_bytes((root/name/'shares.v3').read_bytes()[:len(reference)])
            check = snapshot(name+'-common', common)
            assert (check['tip'], check['ledger']) == (ref['tip'], ref['ledger'])
            result['cases'][name]['full_validated_replay_matches'] = True
            result['cases'][name]['final_height'] = got['height']
        result['reference'] = {k:ref[k] for k in ('height', 'tip', 'work', 'ledger')}
        result['status'] = 'PASS'
        save()
        print('PASS all isolated persistence probes', flush=True)
    finally:
        run(dc + ['stop', '-t', '10'])
        save()


if __name__ == '__main__':
    main()
